---

- name: Adding mparks.
  user:
    name: mparks
    password: fAN0n2f1iPuq6
    shell: /bin/bash
    groups: sshusers
    append: yes
  tags:
      - ssh

- name: Add mparks ssh key
  authorized_key:
    user: mparks
    state: present
    key: "{{ lookup('file', '/home/lance/ansible/ssh/mparks/files/id_ed25519.pub') }}" 
